# Generated by Django 5.1.1 on 2024-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0003_alter_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
